servers/routes/menu/index.ts
src/pages/list/card-list.vue
src/router/dynamic-routes.ts

link https://github.com/antdv-pro/antdv-pro/issues/25

feat: add new card-list page

---

src/layouts/components/sider-menu/index.vue

fix: menu icon #53

---

servers/routes/menu/index.ts
src/components/footer-tool-bar/index.less
src/components/footer-tool-bar/index.md
src/components/footer-tool-bar/index.vue
src/pages/form/advanced-form/index.vue
src/pages/form/advanced-form/repository-form.vue
src/pages/form/advanced-form/task-form.vue
src/router/dynamic-routes.ts

feat: add advanced form

---

src/layouts/components/header/index.vue
src/layouts/components/menu/split-menu.vue
src/layouts/components/sider-menu/index.vue

修复分割菜单功能，无子路由时，sider menu仍占位置的问题

---

servers/routes/list/consult-list.post.ts
servers/routes/menu/index.ts
src/api/list/consult-table.ts
src/locales/lang/global/en-US.ts
src/locales/lang/global/zh-CN.ts
src/pages/list/consult-table.vue
src/router/dynamic-routes.ts
src/utils/constant.ts

feat: add consult-table page

---

src/config/default-setting.ts
src/layouts/basic-layout/context.ts
src/layouts/basic-layout/typing.ts
src/layouts/components/global-header/index.vue
src/layouts/components/header/index.vue
src/layouts/components/setting-drawer/index.vue
src/layouts/components/setting-drawer/layout-setting.vue
src/layouts/components/sider-menu/index.vue
src/layouts/index.vue
src/locales/lang/global/en-US.ts
src/locales/lang/global/zh-CN.ts
src/stores/app.ts

修改侧边栏可伸缩按钮位置

---

src/pages/common/login.vue
unocss.config.ts

fix: login form logo container layout

---

src/pages/dashboard/analysis/components/custom-ring-progress.vue
src/pages/dashboard/analysis/components/top-search.vue
src/pages/dashboard/analysis/introduce-row.vue
src/pages/dashboard/monitor/active-chart.vue
src/pages/dashboard/monitor/custom-map.vue
src/pages/dashboard/monitor/index.vue

fix: chart auto fit

---

src/pages/dashboard/analysis/index.vue
src/pages/dashboard/monitor/index.vue
src/pages/dashboard/workplace/index.vue
src/pages/form/advanced-form/index.vue
src/pages/form/basic-form/index.vue
src/pages/list/search-list/index.vue
src/pages/profile/advanced/index.vue

fix: add `defineOptions` to index file

---

src/config/default-setting.ts
src/layouts/components/setting-drawer/index.vue
src/layouts/components/setting-drawer/regional-setting.vue
src/layouts/index.vue
src/locales/lang/global/en-US.ts
src/locales/lang/global/zh-CN.ts
src/stores/app.ts

add watermark switch in layoutsetting

feat(setting): supported watermark switch

---

src/pages/dashboard/workplace/index.vue

fix: card layout misalignment

---

src/config/default-setting.ts
src/layouts/components/setting-drawer/index.vue
src/layouts/components/setting-drawer/layout-setting.vue
src/layouts/index.vue
src/locales/lang/global/en-US.ts
src/locales/lang/global/zh-CN.ts
src/stores/app.ts

添加紧凑模式主题 无侵入, 测试过没有问题,下面有动图效果:

feat: complete compact-algorithm

---

src/pages/list/table-list.vue

[125](https://github.com/antdv-pro/antdv-pro/issues/125)
作为pro-table开发完成前的临时替代，功能实现的比较简略

feat: query table add toolbar

---

src/layouts/components/global-header/index.vue

fix: x-axis scroll bar appears in top layout mode

---

servers/routes/list/crud-table.post.ts
servers/routes/menu/index.ts
src/api/list/crud-table.ts
src/composables/table-query.ts
src/locales/lang/global/en-US.ts
src/locales/lang/global/zh-CN.ts
src/pages/list/components/crud-table-modal.vue
src/pages/list/crud-table.vue
src/router/dynamic-routes.ts
types/auto-imports.d.ts

For the table crud, I dev a hook for page query. I don't like repackaged component for table and modal, so it's only a hook for reducing copying codes.

feat: add table-query hook for crud table

---

src/components/page-container/index.vue

修复了 https://github.com/antdv-pro/antdv-pro/issues/150
由于有setTimeout原因，还是觉得怪怪的

fix: 路由切换可能导致page-container的头部面包屑等区域被意外隐藏

---

src/layouts/components/sider-menu/index.less

fix: fix title style in slider logo #152

---

src/config/default-setting.ts
src/layouts/components/setting-drawer/index.vue
src/layouts/components/setting-drawer/other-setting.vue
src/layouts/index.vue
src/locales/lang/global/en-US.ts
src/locales/lang/global/zh-CN.ts
src/stores/app.ts

1. 添加灰色模式
2. 修复在配置文件中修改colorWeak为true时打开页面没有默认生效的问题

feat: add gray mode

---

README.md

docs: word spelling mistake

---

src/layouts/multi-tab/index.vue

fix: multi-tab width error

---

public/loading.js

根据W3C动画命名规范，动画名称的命名需要遵循以下规则：
1. 动画名称可以包含字母（a-z 或 A-Z）、数字（0-9）、连字符（-）。
2. 动画名称不能包含空格、下划线和其他特殊字符。
3. 动画名称区分大小写，但建议使用小写字母和连字符（kebab-case）来提高可读性和一致性。

chore: loading animations follows rules

---

src/router/generate-route.ts

fix: 前端路由(dynamicRoutes)权限问题
